openapi: 3.0.0
info:
  title: X-Road Simple Statistics API
  description: This API provides some basic statistics about X-Road instances - member count, Security Server count, subsystem count and list of member classes with member count per member class.
  contact:
    email: <EMAIL>
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: 1.0.0
servers:
- url: https://<HOST>
  description: X-Road Statisctics
paths:
  /instances:
    get:
      summary: get list of available instance identifiers
      description: |
        Get instance identifiers of instances which statistics are available through the API
      responses:
        200:
          description: list of instance identifiers which statistics are available
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstanceIdentifier'
  /instances/{instanceIdentifier}:
    get:
      summary: get current statistics
      description: |
        Get statistics related to a specific X-Road instance
      parameters:
      - name: instanceIdentifier
        in: path
        description: instance identifier of an X-Road instance
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: statistics related to the specified X-Road instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatisticItem'
        400:
          description: bad input parameter
        404:
          description: instance not found
  /instances/{instanceIdentifier}/history:
    get:
      summary: get historical monthly statistics
      description: |
        Get historical monthly statistics related to a specific X-Road instance
      parameters:
      - name: instanceIdentifier
        in: path
        description: instance identifier of an X-Road instance
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: historical monthly statistics related to the specified X-Road instance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatisticItem'
        400:
          description: bad input parameter
        404:
          description: instance not found
components:
  schemas:
    StatisticItem:
      required:
      - date
      - instanceIdentifier
      - memberClasses
      - members
      - securityServers
      - subsystems
      type: object
      properties:
        instanceIdentifier:
          pattern: ^[\w-]{1,255}$
          type: string
          description: X-Road instance identifier
          example: FI
        subsystems:
          type: integer
          description: subsystem count
          format: int32
          example: 100
        securityServers:
          type: integer
          description: Security Server count
          format: int32
          example: 50
        members:
          type: integer
          description: member count
          format: int32
          example: 30
        date:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
          description: date when the data was updated
          example: 2018-08-29
        memberClasses:
          type: array
          description: list of member classes
          items:
            $ref: '#/components/schemas/MemberClass'
    MemberClass:
      required:
      - memberClass
      - memberCount
      type: object
      properties:
        memberClass:
          type: string
          description: member class name
          example: GOV
        memberCount:
          type: integer
          description: number of members in this member class
          format: int32
          example: 50
    InstanceIdentifier:
      required:
      - instanceIdentifier
      type: object
      properties:
        instanceIdentifier:
          type: string
          description: X-Road instance identifier
          example: FI
